export const to = {
  hotelSetup: "/",
  home: "/home",
  bookingId: "/booking-id",
  bookingDetail: "/booking-detail",
  bookingInfo: "/booking-info",
  creditCard: "/credit-card",
  checkIn: "/check-in",
  scanQr: "/scan-qr",
  scanId: "/scan-id",
  thankYou: "/thank-you",
  selectKeys: "/select-keys",
  scanbarCode: "/scan-bar-code",
  confirmDetails: "/confirm-details",
  multiBooking: "/multi-booking",
  terms: "/terms",
  swipeCard: "/swipe-card",
  captureFront:"/capture-front",
  captureFace:"/capture-face",
  videoScreen:"/video-screen",
};
